CREATE TABLE student(
"id" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
"isim"  VARCHAR (25) NOT NULL,
"soyisim" VARCHAR (25) NOT NULL
)


INSERT INTO FAHRI.STUDENT("isim","soyisim") VALUES('asd','ert');