/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajan;

import static ajan.ajanframe.AjanMachine;
import static ajan.ajanframe.AjanPortIn;
import static ajan.ajanframe.CncPrmInit;
import static ajan.ajanframe.gecerliproje;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ajanuser
 */
public class G5xFrame extends javax.swing.JDialog {
    private ReferanslarDb rd=new ReferanslarDb(AjanMachine.referenceID);
    /**
     * Creates new form G5xFrame
     */
    public G5xFrame() {
        initComponents();
        setnameyap();
        degerleri_doldur();
    otomatikbutton.setSelected(true);
    }
    public void setnameyap(){
        G55xbutton.setName("G55xbutton");
        G55ybutton.setName("G55ybutton");
        G55abutton.setName("G55abutton");
        G55cbutton.setName("G55cbutton");
        G55dbutton.setName("G55dbutton");
        
        G56xbutton.setName("G56xbutton");
        G56ybutton.setName("G56ybutton");
        G56abutton.setName("G56abutton");
        G56cbutton.setName("G56cbutton");
        G56dbutton.setName("G56dbutton");
        
        G57xbutton.setName("G57xbutton");
        G57ybutton.setName("G57ybutton");
        G57abutton.setName("G57abutton");
        G57cbutton.setName("G57cbutton");
        G57dbutton.setName("G57dbutton");
        
        G54tumatabutton.setName("G54tumatabutton");
        G55tumatabutton.setName("G55tumatabutton");
        G56tumatabutton.setName("G56tumatabutton");
        G57tumatabutton.setName("G57tumatabutton");
        
    }
public void degerleri_doldur(){

    /*G54xbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G54.X/100).replace(",",".")+" mm");
    G54ybutton.setText(String.format("%.2f", ajanframe.AjanMachine.G54.Y/100).replace(",",".")+" mm");
    G54abutton.setText(String.format("%.2f", ajanframe.AjanMachine.G54.A/100).replace(",",".")+" °");
    G54cbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G54.C/100).replace(",",".")+" °");
    G54dbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G54.D/100).replace(",",".")+" °");
*/
    G54xbutton.setText(String.format("%.2f", rd.getX()/100).replace(",",".")+" mm");
    G54ybutton.setText(String.format("%.2f", rd.getY()/100).replace(",",".")+" mm");
    G54abutton.setText(String.format("%.2f", rd.getA()/100).replace(",",".")+" °");
    G54cbutton.setText(String.format("%.2f", rd.getC()/100).replace(",",".")+" °");
    G54dbutton.setText(String.format("%.2f", rd.getD()/100).replace(",",".")+" °");
    
    G55xbutton.setText(String.format("%.2f", (float)gecerliproje.aposx/100).replace(",",".")+" mm");
    G55ybutton.setText(String.format("%.2f", (float)gecerliproje.aposy/100).replace(",",".")+" mm");
    G55abutton.setText(String.format("%.2f", (float)gecerliproje.aposa/100).replace(",",".")+" °");
    G55cbutton.setText(String.format("%.2f", (float)gecerliproje.aposc/100).replace(",",".")+" °");
    G55dbutton.setText(String.format("%.2f", (float)gecerliproje.aposd/100).replace(",",".")+" °");
    
    G56xbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G56.X/100).replace(",",".")+" mm");
    G56ybutton.setText(String.format("%.2f", ajanframe.AjanMachine.G56.Y/100).replace(",",".")+" mm");
    G56abutton.setText(String.format("%.2f", ajanframe.AjanMachine.G56.A/100).replace(",",".")+" °");
    G56cbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G56.C/100).replace(",",".")+" °");
    G56dbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G56.D/100).replace(",",".")+" °");
    
    G57xbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G57.X/100).replace(",",".")+" mm");
    G57ybutton.setText(String.format("%.2f", ajanframe.AjanMachine.G57.Y/100).replace(",",".")+" mm");
    G57abutton.setText(String.format("%.2f", ajanframe.AjanMachine.G57.A/100).replace(",",".")+" °");
    G57cbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G57.C/100).replace(",",".")+" °");
    G57dbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G57.D/100).replace(",",".")+" °");
    
    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        G54xbutton = new javax.swing.JButton();
        G54ybutton = new javax.swing.JButton();
        G54abutton = new javax.swing.JButton();
        G54cbutton = new javax.swing.JButton();
        G54dbutton = new javax.swing.JButton();
        G55xbutton = new javax.swing.JButton();
        G55ybutton = new javax.swing.JButton();
        G55abutton = new javax.swing.JButton();
        G55cbutton = new javax.swing.JButton();
        G55dbutton = new javax.swing.JButton();
        G56xbutton = new javax.swing.JButton();
        G56ybutton = new javax.swing.JButton();
        G56abutton = new javax.swing.JButton();
        G56cbutton = new javax.swing.JButton();
        G56dbutton = new javax.swing.JButton();
        G57xbutton = new javax.swing.JButton();
        G57ybutton = new javax.swing.JButton();
        G57abutton = new javax.swing.JButton();
        G57cbutton = new javax.swing.JButton();
        G57dbutton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        G54tumatabutton = new javax.swing.JButton();
        G55tumatabutton = new javax.swing.JButton();
        G56tumatabutton = new javax.swing.JButton();
        G57tumatabutton = new javax.swing.JButton();
        manuelmutlakbutton = new javax.swing.JToggleButton();
        otomatikbutton = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("<html>SIFIR<br>NOKTASI</html>");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("G55");
        jLabel2.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("G56");
        jLabel3.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("G57");
        jLabel4.setEnabled(false);

        G54xbutton.setBackground(new java.awt.Color(255, 115, 8));
        G54xbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G54xbutton.setText("325.25 mm");
        G54xbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "X", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G54xbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G54xbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G54xbuttonActionPerformed(evt);
            }
        });

        G54ybutton.setBackground(new java.awt.Color(255, 51, 204));
        G54ybutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G54ybutton.setText("325.25 mm");
        G54ybutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Y", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G54ybutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G54ybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G54ybuttonActionPerformed(evt);
            }
        });

        G54abutton.setBackground(new java.awt.Color(255, 153, 153));
        G54abutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G54abutton.setText("0.00 °");
        G54abutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "A", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G54abutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G54abutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G54abuttonActionPerformed(evt);
            }
        });

        G54cbutton.setBackground(new java.awt.Color(0, 204, 204));
        G54cbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G54cbutton.setText("0.00 °");
        G54cbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "C", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G54cbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G54cbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G54cbuttonActionPerformed(evt);
            }
        });

        G54dbutton.setBackground(new java.awt.Color(235, 99, 225));
        G54dbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G54dbutton.setText("0.00 °");
        G54dbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "D", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G54dbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G54dbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G54dbuttonActionPerformed(evt);
            }
        });

        G55xbutton.setBackground(new java.awt.Color(255, 115, 8));
        G55xbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G55xbutton.setText("325.25 mm");
        G55xbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "X", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G55xbutton.setEnabled(false);
        G55xbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G55xbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G55xbuttonActionPerformed(evt);
            }
        });

        G55ybutton.setBackground(new java.awt.Color(255, 51, 204));
        G55ybutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G55ybutton.setText("325.25 mm");
        G55ybutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Y", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G55ybutton.setEnabled(false);
        G55ybutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G55ybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G55ybuttonActionPerformed(evt);
            }
        });

        G55abutton.setBackground(new java.awt.Color(255, 153, 153));
        G55abutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G55abutton.setText("0.00 °");
        G55abutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "A", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G55abutton.setEnabled(false);
        G55abutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G55abutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G55abuttonActionPerformed(evt);
            }
        });

        G55cbutton.setBackground(new java.awt.Color(0, 204, 204));
        G55cbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G55cbutton.setText("0.00 °");
        G55cbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "C", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G55cbutton.setEnabled(false);
        G55cbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G55cbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G55cbuttonActionPerformed(evt);
            }
        });

        G55dbutton.setBackground(new java.awt.Color(235, 99, 225));
        G55dbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G55dbutton.setText("0.00 °");
        G55dbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "D", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G55dbutton.setEnabled(false);
        G55dbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G55dbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G55dbuttonActionPerformed(evt);
            }
        });

        G56xbutton.setBackground(new java.awt.Color(255, 115, 8));
        G56xbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G56xbutton.setText("325.25 mm");
        G56xbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "X", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G56xbutton.setEnabled(false);
        G56xbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G56xbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G56xbuttonActionPerformed(evt);
            }
        });

        G56ybutton.setBackground(new java.awt.Color(255, 51, 204));
        G56ybutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G56ybutton.setText("325.25 mm");
        G56ybutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Y", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G56ybutton.setEnabled(false);
        G56ybutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G56ybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G56ybuttonActionPerformed(evt);
            }
        });

        G56abutton.setBackground(new java.awt.Color(255, 153, 153));
        G56abutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G56abutton.setText("0.00 °");
        G56abutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "A", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G56abutton.setEnabled(false);
        G56abutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G56abutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G56abuttonActionPerformed(evt);
            }
        });

        G56cbutton.setBackground(new java.awt.Color(0, 204, 204));
        G56cbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G56cbutton.setText("0.00 °");
        G56cbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "C", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G56cbutton.setEnabled(false);
        G56cbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G56cbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G56cbuttonActionPerformed(evt);
            }
        });

        G56dbutton.setBackground(new java.awt.Color(235, 99, 225));
        G56dbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G56dbutton.setText("0.00 °");
        G56dbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "D", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G56dbutton.setEnabled(false);
        G56dbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G56dbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G56dbuttonActionPerformed(evt);
            }
        });

        G57xbutton.setBackground(new java.awt.Color(255, 115, 8));
        G57xbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G57xbutton.setText("325.25 mm");
        G57xbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "X", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G57xbutton.setEnabled(false);
        G57xbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G57xbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G57xbuttonActionPerformed(evt);
            }
        });

        G57ybutton.setBackground(new java.awt.Color(255, 51, 204));
        G57ybutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G57ybutton.setText("325.25 mm");
        G57ybutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Y", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G57ybutton.setEnabled(false);
        G57ybutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G57ybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G57ybuttonActionPerformed(evt);
            }
        });

        G57abutton.setBackground(new java.awt.Color(255, 153, 153));
        G57abutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G57abutton.setText("0.00 °");
        G57abutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "A", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G57abutton.setEnabled(false);
        G57abutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G57abutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G57abuttonActionPerformed(evt);
            }
        });

        G57cbutton.setBackground(new java.awt.Color(0, 204, 204));
        G57cbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G57cbutton.setText("0.00 °");
        G57cbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "C", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G57cbutton.setEnabled(false);
        G57cbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G57cbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G57cbuttonActionPerformed(evt);
            }
        });

        G57dbutton.setBackground(new java.awt.Color(235, 99, 225));
        G57dbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G57dbutton.setText("0.00 °");
        G57dbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "D", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G57dbutton.setEnabled(false);
        G57dbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        G57dbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G57dbuttonActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(235, 99, 225));

        jSeparator2.setBackground(new java.awt.Color(235, 99, 225));

        jSeparator3.setBackground(new java.awt.Color(235, 99, 225));

        G54tumatabutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G54tumatabutton.setText("HEPSİNİ ATA");
        G54tumatabutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G54tumatabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G54tumatabuttonActionPerformed(evt);
            }
        });

        G55tumatabutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G55tumatabutton.setText("HEPSİNİ ATA");
        G55tumatabutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G55tumatabutton.setEnabled(false);
        G55tumatabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G55tumatabuttonActionPerformed(evt);
            }
        });

        G56tumatabutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G56tumatabutton.setText("HEPSİNİ ATA");
        G56tumatabutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G56tumatabutton.setEnabled(false);
        G56tumatabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G56tumatabuttonActionPerformed(evt);
            }
        });

        G57tumatabutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        G57tumatabutton.setText("HEPSİNİ ATA");
        G57tumatabutton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        G57tumatabutton.setEnabled(false);
        G57tumatabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G57tumatabuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(G54tumatabutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G54xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G54ybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G54abutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G54cbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G54dbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(G55tumatabutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(8, 8, 8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(20, 20, 20)
                                        .addComponent(G56tumatabutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(20, 20, 20)
                                        .addComponent(G57tumatabutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(G55xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G55ybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G55abutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G55cbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G55dbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(G56xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G56ybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G56abutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G56cbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G56dbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(G57xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G57ybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G57abutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G57cbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G57dbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(G54xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G54ybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G54abutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G54cbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G54dbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G54tumatabutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(G55xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G55ybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G55abutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G55cbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G55dbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(G55tumatabutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(G56xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G56ybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G56abutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G56cbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G56dbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(G56tumatabutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(G57xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G57ybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G57abutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G57cbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G57dbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(G57tumatabutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        G54xbutton.setName("G54xbutton");
        G54ybutton.setName("G54ybutton");
        G54abutton.setName("G54abutton");
        G54cbutton.setName("G54cbutton");
        G54dbutton.setName("G54dbutton");

        buttonGroup1.add(manuelmutlakbutton);
        manuelmutlakbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manuelmutlakbutton.setText("MANUEL");
        manuelmutlakbutton.setToolTipText("Atama Yapmak istediğiniz eksene tıklayın");
        manuelmutlakbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuelmutlakbuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(otomatikbutton);
        otomatikbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        otomatikbutton.setText("OTOMATİK");
        otomatikbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otomatikbuttonActionPerformed(evt);
            }
        });

        jButton1.setText("GOZERO");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(otomatikbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manuelmutlakbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {manuelmutlakbutton, otomatikbutton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(manuelmutlakbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(otomatikbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public String DegerAl(String gelen){
    gelen=gelen.replace("mm", "");
     gelen=gelen.replace("°", "");
float f=Float.parseFloat(gelen);
//String num = gelen.replace("/[^0-9]/g",'');

return String.format("%.2f", f).replace(",",".");
}
Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();

public static String gelenDeger=null;


public void degerAl(javax.swing.JButton but)
{
    
    
boolean degree=false;
Color oldColor=but.getBackground();
if(!otomatikbutton.isSelected())
{

//but.setBackground(Color.DARK_GRAY);
but.setBackground(Color.getHSBColor(240,240, 240));
if(but.getText().endsWith("°"))degree=true;
DialogAxesInputFrame dfr=new DialogAxesInputFrame("Deger Girin : ",DegerAl(but.getText()),Color.getHSBColor(240,240, 240));
dfr.setLocation(jPanel1.getX()+ but.getLocation().x+ this.getX()+10,jPanel1.getY()+ this.getY()+ but.getLocation().y+(but.getHeight()+30));
dfr.setModal(true);
dfr.show();

if(gelenDeger!=null)
{

    String s = gelenDeger;
    
    if ((s != null) && (s.length() > 0)) 
    {
            s=s.replace(",",".");
            float f=Float.parseFloat(s)*100;
  /*          
            if(degree==true) but.setText(String.format("%.2f", f).replace(",",".")+" °" );
            else
                but.setText(String.format("%.2f", f).replace(",",".")+" mm" );
*/            

//return;
        int result= JOptionPane.showConfirmDialog(null, "Atama Yapılsın mı?", "ATAMA ONAY PENCERESİ", JOptionPane.YES_NO_OPTION);
            
        if(result==0){
        
        switch (but.getName()) {
        
        case "G54xbutton":rd.setX(f);break;
        case "G54ybutton":rd.setY(f);break;
        case "G54abutton":rd.setA(f);break;
        case "G54cbutton":rd.setC(f);break;
        case "G54dbutton":rd.setD(f);break;  
        
        /*case "G54xbutton": ajanframe.AjanMachine.G54.X=f;break;
        case "G54ybutton":ajanframe.AjanMachine.G54.Y=f;break;
        case "G54abutton":ajanframe.AjanMachine.G54.A=f;break;
        case "G54cbutton":ajanframe.AjanMachine.G54.C=f;break;
        case "G54dbutton":ajanframe.AjanMachine.G54.D=f;break;*/

        
        case "G55xbutton": ajanframe.AjanMachine.G55.X=f;break;
        case "G55ybutton":ajanframe.AjanMachine.G55.Y=f;break;
        case "G55abutton":ajanframe.AjanMachine.G55.A=f;break;
        case "G55cbutton":ajanframe.AjanMachine.G55.C=f;break;
        case "G55dbutton":ajanframe.AjanMachine.G55.D=f;break;

        
        case "G56xbutton": ajanframe.AjanMachine.G56.X=f;break;
        case "G56ybutton":ajanframe.AjanMachine.G56.Y=f;break;
        case "G56abutton":ajanframe.AjanMachine.G56.A=f;break;
        case "G56cbutton":ajanframe.AjanMachine.G56.C=f;break;
        case "G56dbutton":ajanframe.AjanMachine.G56.D=f;break;

        
        case "G57xbutton": ajanframe.AjanMachine.G57.X=f;break;
        case "G57ybutton":ajanframe.AjanMachine.G57.Y=f;break;
        case "G57abutton":ajanframe.AjanMachine.G57.A=f;break;
        case "G57cbutton":ajanframe.AjanMachine.G57.C=f;break;
        case "G57dbutton":ajanframe.AjanMachine.G57.D=f;break;

            
        default:
            break;
    }
 
                    rd.referansYaz_Var(AjanMachine.referenceID);
                    degerleri_doldur();
            
            }
    }
}



}
else {



int result= JOptionPane.showConfirmDialog(null, "Atama Yapılsın mı?", "ATAMA ONAY PENCERESİ", JOptionPane.YES_NO_OPTION);

if(result==0){ //but.setText("55.55 mm");
    switch (but.getName()) {
        case "G54xbutton":
            //ajanframe.AjanMachine.G54.X=ajanframe.AjanPortIn.PosX;
            rd.setX(ajanframe.AjanPortIn.APosX);
            G54xbutton.setText(String.format("%.2f", rd.getX()/100).replace(",",".")+" mm");
            break;
        case "G54ybutton":
            //ajanframe.AjanMachine.G54.Y=ajanframe.AjanPortIn.PosY;
            rd.setY(ajanframe.AjanPortIn.PosY);
            G54ybutton.setText(String.format("%.2f", rd.getY()/100).replace(",",".")+" mm");
            break;
        case "G54abutton":
            //ajanframe.AjanMachine.G54.A=ajanframe.AjanPortIn.PosA;
            rd.setA(ajanframe.AjanPortIn.PosA);
            G54abutton.setText(String.format("%.2f", rd.getA()/100).replace(",",".")+" °");
            break;
        case "G54cbutton":
            //ajanframe.AjanMachine.G54.C=ajanframe.AjanPortIn.PosC;
            rd.setC(ajanframe.AjanPortIn.PosC);
            G54cbutton.setText(String.format("%.2f", rd.getC()/100).replace(",",".")+" °");
            break;
        case "G54dbutton":
            //ajanframe.AjanMachine.G54.D=ajanframe.AjanPortIn.PosD;
            rd.setD(ajanframe.AjanPortIn.PosD);
            G54dbutton.setText(String.format("%.2f", rd.getD()/100).replace(",",".")+" °");
            break;
        

        case "G55xbutton":
            ajanframe.AjanMachine.G55.X=ajanframe.AjanPortIn.PosX;
            G55xbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G55.X/100).replace(",",".")+" mm");
            break;
        case "G55ybutton":
            ajanframe.AjanMachine.G55.Y=ajanframe.AjanPortIn.PosY;
            G55ybutton.setText(String.format("%.2f", ajanframe.AjanMachine.G55.Y/100).replace(",",".")+" mm");
            break;
        case "G55abutton":
            ajanframe.AjanMachine.G55.A=ajanframe.AjanPortIn.PosA;
            G55abutton.setText(String.format("%.2f", ajanframe.AjanMachine.G55.A/100).replace(",",".")+" °");
            break;
        case "G55cbutton":
            ajanframe.AjanMachine.G55.C=ajanframe.AjanPortIn.PosC;
            G55cbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G55.C/100).replace(",",".")+" °");
            break;
        case "G55dbutton":
            ajanframe.AjanMachine.G55.D=ajanframe.AjanPortIn.PosD;
            G55dbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G55.D/100).replace(",",".")+" °");
            break;


        case "G56xbutton":
            ajanframe.AjanMachine.G56.X=ajanframe.AjanPortIn.PosX;
            G56xbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G56.X/100).replace(",",".")+" mm");
            break;
        case "G56ybutton":
            ajanframe.AjanMachine.G56.Y=ajanframe.AjanPortIn.PosY;
            G56ybutton.setText(String.format("%.2f", ajanframe.AjanMachine.G56.Y/100).replace(",",".")+" mm");
            break;
        case "G56abutton":
            ajanframe.AjanMachine.G56.A=ajanframe.AjanPortIn.PosA;
            G56abutton.setText(String.format("%.2f", ajanframe.AjanMachine.G56.A/100).replace(",",".")+" °");
            break;
        case "G56cbutton":
            ajanframe.AjanMachine.G56.C=ajanframe.AjanPortIn.PosC;
            G56cbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G56.C/100).replace(",",".")+" °");
            break;
        case "G56dbutton":
            ajanframe.AjanMachine.G56.D=ajanframe.AjanPortIn.PosD;
            G56dbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G56.D/100).replace(",",".")+" °");
            break;

        case "G57xbutton":
            ajanframe.AjanMachine.G57.X=ajanframe.AjanPortIn.PosX;
            G57xbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G57.X/100).replace(",",".")+" mm");
            break;
        case "G57ybutton":
            ajanframe.AjanMachine.G57.Y=ajanframe.AjanPortIn.PosY;
            G57ybutton.setText(String.format("%.2f", ajanframe.AjanMachine.G57.Y/100).replace(",",".")+" mm");
            break;
        case "G57abutton":
            ajanframe.AjanMachine.G57.A=ajanframe.AjanPortIn.PosA;
            G57abutton.setText(String.format("%.2f", ajanframe.AjanMachine.G57.A/100).replace(",",".")+" °");
            break;
        case "G57cbutton":
            ajanframe.AjanMachine.G57.C=ajanframe.AjanPortIn.PosC;
            G57cbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G57.C/100).replace(",",".")+" °");
            break;
        case "G57dbutton":
            ajanframe.AjanMachine.G57.D=ajanframe.AjanPortIn.PosD;
            G57dbutton.setText(String.format("%.2f", ajanframe.AjanMachine.G57.D/100).replace(",",".")+" °");
            break;
            
            
        default:
            break;
    }
             
    rd.referansYaz_Var(AjanMachine.referenceID);
}

}
but.setBackground(oldColor);
}


public void tumata(javax.swing.JButton but)
{
   
boolean degree=false;
Color oldColor=but.getBackground();
if(otomatikbutton.isSelected())
{

int result= JOptionPane.showConfirmDialog(null, "Tüm Eksenler Atama Yapılsın mı?", "ATAMA ONAY PENCERESİ", 
                                JOptionPane.YES_NO_OPTION);

if(result==0){ //but.setText("55.55 mm");
    
    switch (but.getName()) {
        case "G54tumatabutton":
            /*ajanframe.AjanMachine.G54.X=ajanframe.AjanPortIn.PosX;
            ajanframe.AjanMachine.G54.Y=ajanframe.AjanPortIn.PosY;
            ajanframe.AjanMachine.G54.A=ajanframe.AjanPortIn.PosA;
            ajanframe.AjanMachine.G54.C=ajanframe.AjanPortIn.PosC;
            ajanframe.AjanMachine.G54.D=ajanframe.AjanPortIn.PosD;*/
            rd.setX(ajanframe.AjanPortIn.APosX);
            rd.setY(ajanframe.AjanPortIn.APosY);
            rd.setA(ajanframe.AjanPortIn.APosA);
            rd.setC(ajanframe.AjanPortIn.PosC);
            rd.setD(ajanframe.AjanPortIn.PosD);
            
            break;

        case "G55tumatabutton":
            ajanframe.AjanMachine.G55.X=ajanframe.AjanPortIn.PosX;
            ajanframe.AjanMachine.G55.Y=ajanframe.AjanPortIn.PosY;
            ajanframe.AjanMachine.G55.A=ajanframe.AjanPortIn.PosA;
            ajanframe.AjanMachine.G55.C=ajanframe.AjanPortIn.PosC;
            ajanframe.AjanMachine.G55.D=ajanframe.AjanPortIn.PosD;
            break;

        case "G56tumatabutton":
            ajanframe.AjanMachine.G56.X=ajanframe.AjanPortIn.PosX;
            ajanframe.AjanMachine.G56.Y=ajanframe.AjanPortIn.PosY;
            ajanframe.AjanMachine.G56.A=ajanframe.AjanPortIn.PosA;
            ajanframe.AjanMachine.G56.C=ajanframe.AjanPortIn.PosC;
            ajanframe.AjanMachine.G56.D=ajanframe.AjanPortIn.PosD;
            break;

        case "G57tumatabutton":
            ajanframe.AjanMachine.G57.X=ajanframe.AjanPortIn.PosX;
            ajanframe.AjanMachine.G57.Y=ajanframe.AjanPortIn.PosY;
            ajanframe.AjanMachine.G57.A=ajanframe.AjanPortIn.PosA;
            ajanframe.AjanMachine.G57.C=ajanframe.AjanPortIn.PosC;
            ajanframe.AjanMachine.G57.D=ajanframe.AjanPortIn.PosD;
            break;
            
            
        default:
            break;
    }
    
    rd.referansYaz_Var(AjanMachine.referenceID);
    degerleri_doldur();
             

}
else { but.setText("0.00 mm");}
}
but.setBackground(oldColor);
}







    private void G54xbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G54xbuttonActionPerformed
        // TODO add your handling code here:
        //String deger=DegerAl(jButton1.getText());
        
degerAl(G54xbutton);        
        
/*        
        Color oldColor=jButton1.getBackground();
        jButton1.setBackground(Color.DARK_GRAY);
        //this.setOpacity(0.5f);
        DialogAxesInputFrame dfr=new DialogAxesInputFrame("G54 X Ekseni : ",DegerAl(jButton1.getText()),Color.DARK_GRAY);
        //dfr.setLocation(dim.width/2 - dfr.getSize().width/2 , dim.height/2 - dfr.getSize().height/2);
dfr.setLocation(jPanel1.getX()+ jButton1.getLocation().x+ this.getX()+10,jPanel1.getY()+ this.getY()+ jButton1.getLocation().y+(jButton1.getHeight()+30));
dfr.setModal(true);
dfr.show();

if(gelenDeger!=null){
        //String s = (String)JOptionPane.showInputDialog(this,"G54 X Ekseni Değerini Girin:\n",DegerAl(jButton1.getText()));//DegerAl(jButton1.getText()
String s = gelenDeger;//(String)JOptionPane.showInputDialog(this,"G54 X Ekseni Değerini Girin:\n",DegerAl(jButton1.getText()));//DegerAl(jButton1.getText()
    
//If a string was returned, say so.
if ((s != null) && (s.length() > 0)) {
    s=s.replace(",",".");
    float f=Float.parseFloat(s);
    jButton1.setText(String.format("%.2f", f).replace(",",".")+" mm" );
    //return;
    }
}
//this.setEnabled(true);
//this.setOpacity(1f);
jButton1.setBackground(oldColor);*/

    }//GEN-LAST:event_G54xbuttonActionPerformed

    private void G54ybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G54ybuttonActionPerformed
        // TODO add your handling code here:
degerAl(G54ybutton); 
    }//GEN-LAST:event_G54ybuttonActionPerformed

    private void G54abuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G54abuttonActionPerformed
        // TODO add your handling code here:
degerAl(G54abutton); 
    }//GEN-LAST:event_G54abuttonActionPerformed

    private void G54cbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G54cbuttonActionPerformed
        // TODO add your handling code here:
degerAl(G54cbutton); 
    }//GEN-LAST:event_G54cbuttonActionPerformed

    private void G54dbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G54dbuttonActionPerformed
        // TODO add your handling code here:
degerAl(G54dbutton); 
    }//GEN-LAST:event_G54dbuttonActionPerformed

    private void G55xbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G55xbuttonActionPerformed
        // TODO add your handling code here:
degerAl(G55xbutton); 
    }//GEN-LAST:event_G55xbuttonActionPerformed

    private void G55ybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G55ybuttonActionPerformed
        // TODO add your handling code here:
degerAl(G55ybutton); 
    }//GEN-LAST:event_G55ybuttonActionPerformed

    private void G55abuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G55abuttonActionPerformed
        // TODO add your handling code here:
degerAl(G55abutton); 
    }//GEN-LAST:event_G55abuttonActionPerformed

    private void G55cbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G55cbuttonActionPerformed
        // TODO add your handling code here:
degerAl(G55cbutton); 
    }//GEN-LAST:event_G55cbuttonActionPerformed

    private void G55dbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G55dbuttonActionPerformed
        // TODO add your handling code here:
degerAl(G55dbutton); 
    }//GEN-LAST:event_G55dbuttonActionPerformed

    private void G56xbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G56xbuttonActionPerformed
        // TODO add your handling code here:
degerAl(G56xbutton); 
    }//GEN-LAST:event_G56xbuttonActionPerformed

    private void G56ybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G56ybuttonActionPerformed
        // TODO add your handling code here:
degerAl(G56ybutton); 
    }//GEN-LAST:event_G56ybuttonActionPerformed

    private void G56abuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G56abuttonActionPerformed
        // TODO add your handling code here:
degerAl(G56abutton); 
    }//GEN-LAST:event_G56abuttonActionPerformed

    private void G56cbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G56cbuttonActionPerformed
        // TODO add your handling code here:
degerAl(G56cbutton); 
    }//GEN-LAST:event_G56cbuttonActionPerformed

    private void G56dbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G56dbuttonActionPerformed
        // TODO add your handling code here:
degerAl(G56dbutton); 
    }//GEN-LAST:event_G56dbuttonActionPerformed

    private void G57xbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G57xbuttonActionPerformed
        // TODO add your handling code here:
degerAl(G57xbutton); 
    }//GEN-LAST:event_G57xbuttonActionPerformed

    private void G57ybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G57ybuttonActionPerformed
        // TODO add your handling code here:
degerAl(G57ybutton); 
    }//GEN-LAST:event_G57ybuttonActionPerformed

    private void G57abuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G57abuttonActionPerformed
        // TODO add your handling code here:
degerAl(G57abutton); 
    }//GEN-LAST:event_G57abuttonActionPerformed

    private void G57cbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G57cbuttonActionPerformed
        // TODO add your handling code here:
degerAl(G57cbutton); 
    }//GEN-LAST:event_G57cbuttonActionPerformed

    private void G57dbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G57dbuttonActionPerformed
        // TODO add your handling code here:
degerAl(G57dbutton); 
    }//GEN-LAST:event_G57dbuttonActionPerformed

    private void G54tumatabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G54tumatabuttonActionPerformed
        // TODO add your handling code here:
    tumata(G54tumatabutton);
    /*CncPrmInit.g5x=(int)AjanPortIn.APosX;
    CncPrmInit.g5y=(int)AjanPortIn.APosY; 
                    gecerliproje.aposx = 0;
                    gecerliproje.aposy = 0;
                    
                    dispose();*/
    }//GEN-LAST:event_G54tumatabuttonActionPerformed

    private void G55tumatabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G55tumatabuttonActionPerformed
        // TODO add your handling code here:
        tumata(G55tumatabutton);
    }//GEN-LAST:event_G55tumatabuttonActionPerformed

    private void G56tumatabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G56tumatabuttonActionPerformed
        // TODO add your handling code here:
        tumata(G56tumatabutton);
    }//GEN-LAST:event_G56tumatabuttonActionPerformed

    private void G57tumatabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G57tumatabuttonActionPerformed
        // TODO add your handling code here:
        tumata(G57tumatabutton);
    }//GEN-LAST:event_G57tumatabuttonActionPerformed

    private void manuelmutlakbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuelmutlakbuttonActionPerformed
        // TODO add your handling code here:
    if(otomatikbutton.isSelected()){
        G54tumatabutton.setEnabled(true);
        G55tumatabutton.setEnabled(true);
        G56tumatabutton.setEnabled(true);
        G57tumatabutton.setEnabled(true);
        G54xbutton.setForeground(Color.lightGray);
        //G54xbutton.set
    }
    else 
    {
        G54tumatabutton.setEnabled(false);
        G55tumatabutton.setEnabled(false);
        G56tumatabutton.setEnabled(false);
        G57tumatabutton.setEnabled(false);
    }

    }//GEN-LAST:event_manuelmutlakbuttonActionPerformed

    private void otomatikbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otomatikbuttonActionPerformed
        // TODO add your handling code here:
if(otomatikbutton.isSelected()){
        G54tumatabutton.setEnabled(true);
        G55tumatabutton.setEnabled(true);
        G56tumatabutton.setEnabled(true);
        G57tumatabutton.setEnabled(true);
        //G54xbutton.setForeground(Color.lightGray);

    }
    else 
    {
        G54tumatabutton.setEnabled(false);
        G55tumatabutton.setEnabled(false);
        G56tumatabutton.setEnabled(false);
        G57tumatabutton.setEnabled(false);
    }
    }//GEN-LAST:event_otomatikbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
  

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
   if(AjanPortIn.stat.MachineZeroOk){
                      //  AjanMachine.G54.X = AjanPortIn.APosX;
                      //  AjanMachine.G54.Y = AjanPortIn.APosY;
                        CncPrmInit.g5x=(int)rd.getX();//gecerliproje.aposx;
                        CncPrmInit.g5y=(int)rd.getY();//gecerliproje.aposy;
                        //CncPrmInit.ata=1;
                        try {
                                TimeUnit.MILLISECONDS.sleep(200);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(G5xFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        ajanframe.CncPrmInit.komut = 'P';
        }else {
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Go Machine Zero ", "Warning", dialogButton);//degree alt+248
        if(dialogResult == 0) {
        
         //Job.PlateToXAxisAngle=(float)(angle*180/Math.PI); 
        
        }
        
        }
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
                            CncPrmInit.g5x=0;
                        CncPrmInit.g5y=0;
                        CncPrmInit.ata=0;
    }//GEN-LAST:event_jButton1MouseReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ajanframe.GostergeAyarla();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(G5xFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(G5xFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(G5xFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(G5xFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new G5xFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton G54abutton;
    private javax.swing.JButton G54cbutton;
    private javax.swing.JButton G54dbutton;
    private javax.swing.JButton G54tumatabutton;
    private javax.swing.JButton G54xbutton;
    private javax.swing.JButton G54ybutton;
    private javax.swing.JButton G55abutton;
    private javax.swing.JButton G55cbutton;
    private javax.swing.JButton G55dbutton;
    private javax.swing.JButton G55tumatabutton;
    private javax.swing.JButton G55xbutton;
    private javax.swing.JButton G55ybutton;
    private javax.swing.JButton G56abutton;
    private javax.swing.JButton G56cbutton;
    private javax.swing.JButton G56dbutton;
    private javax.swing.JButton G56tumatabutton;
    private javax.swing.JButton G56xbutton;
    private javax.swing.JButton G56ybutton;
    private javax.swing.JButton G57abutton;
    private javax.swing.JButton G57cbutton;
    private javax.swing.JButton G57dbutton;
    private javax.swing.JButton G57tumatabutton;
    private javax.swing.JButton G57xbutton;
    private javax.swing.JButton G57ybutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton manuelmutlakbutton;
    private javax.swing.JToggleButton otomatikbutton;
    // End of variables declaration//GEN-END:variables
}
