/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajan;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author ajanuser
 */
public class HataFotolari extends javax.swing.JFrame {

    /**
     * Creates new form HataFotolari
     */
//    public String HataMesaji="HATA";
    public HataFotolari() {
        initComponents();
        
        Dimension screenSize,frameSize;
int x,y;
screenSize=Toolkit.getDefaultToolkit().getScreenSize();
frameSize=getSize();
x=(screenSize.width-frameSize.width)/2;
y=(screenSize.height-frameSize.height)/2;
setLocation(x, y);

    }
    public void etiketyaz(String HataMesaji){
    jLabel2.setText(HataMesaji);
    
         if(HataMesaji.compareTo("X Driver Fault")==0)HataMesaji="Hataxsurucu";
    else if(HataMesaji.compareTo("C Driver Fault")==0)HataMesaji="Hatacsurucu";
    else if(HataMesaji.compareTo("A Driver Fault")==0)HataMesaji="Hataasurucu";
    else if(HataMesaji.compareTo("Y Driver Fault")==0)HataMesaji="Hataysurucu";
    else if(HataMesaji.compareTo("D Driver Fault")==0)HataMesaji="Hatadsurucu";
    
    else if(HataMesaji.compareTo("TL Driver Fault")==0)HataMesaji="Hatatlsurucu";
    else if(HataMesaji.compareTo("TR Driver Fault")==0)HataMesaji="Hatatrsurucu";
    else if(HataMesaji.compareTo("TV Driver Fault")==0)HataMesaji="Hatatvsurucu";
    else if(HataMesaji.compareTo("TW Driver Fault")==0)HataMesaji="Hatatwsurucu";
    

    else if(HataMesaji.compareTo("+ X Limit")==0)HataMesaji="Hataartixlimit";
    else if(HataMesaji.compareTo("- X Limit")==0)HataMesaji="Hataeksixlimit";
    else if(HataMesaji.compareTo("+ Y Limit")==0)HataMesaji="Hataartiylimit";
    else if(HataMesaji.compareTo("- Y Limit")==0||HataMesaji.compareTo("- Y Limite")==0)HataMesaji="Hataeksiylimit";
    else if(HataMesaji.compareTo("+ TRLimit")==0)HataMesaji="Hataartitrlimit";
    else if(HataMesaji.compareTo("- TRLimit")==0)HataMesaji="Hataeksitrlimit";
    else if(HataMesaji.compareTo("+ TLLimit")==0)HataMesaji="Hataartitllimit";
    else if(HataMesaji.compareTo("- TLLimit")==0)HataMesaji="Hataeksitllimit";
    else if(HataMesaji.compareTo("+ TVLimit")==0)HataMesaji="Hataartitllimit";
    else if(HataMesaji.compareTo("- TVLimit")==0)HataMesaji="Hataeksitllimit";
    else if(HataMesaji.compareTo("+ TWLimit")==0)HataMesaji="Hataartitllimit";
    else if(HataMesaji.compareTo("- TWLimit")==0)HataMesaji="Hataeksitllimit";
    
    
    
    else if(HataMesaji.compareTo("TL Torch Contact")==0||HataMesaji.compareTo("TV Torch Contact")==0||HataMesaji.compareTo("TW Torch Contact")==0)HataMesaji="Hataihstl";
    else if(HataMesaji.compareTo("TR Torch Contact")==0)HataMesaji="Hataihstr";
    
    else if(HataMesaji.compareTo("TL Torch Crashed")==0||HataMesaji.compareTo("TR Torch Crashed")==0||HataMesaji.compareTo("TV Torch Crashed")==0||HataMesaji.compareTo("TW Torch Crashed")==0)HataMesaji="Hatacarpma";
    
    
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajanimages/newpackage/hata/"+HataMesaji+".jpg"))); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("HataFotolari"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajanimages/newpackage/hata/Hataartixlimit.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HataFotolari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HataFotolari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HataFotolari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HataFotolari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HataFotolari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
