/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajan;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author ajanuser
 */
public class Hatalar extends javax.swing.JFrame {

    /**
     * Creates new form Hatalar
     */
/*public void paintComponent(Graphics g){
super.paintComponents(g);
if(getY()==(dim.height/2-this.getSize().height/2)&&kapat==false){tm.stop();timeracik=false;}
else if(getY()<2000&&kapat==true){tm.stop();timeracik=false;}
}*/


    static Timer tm;boolean kapat=false;boolean timeracik=false;
    Dimension dim;int xgelen=0;int ygelen=0;
    public Hatalar() {
        initComponents();
        dim= Toolkit.getDefaultToolkit().getScreenSize();
        
        tm=new Timer(5,new ActionListener(){
            public void actionPerformed(ActionEvent e){
                if(kapat==true){
                
                    if(getX()<x2)setLocation(getX()+13,getY());
                    else if(getX()>x2)setLocation(getX()-13,getY());
                    if(getY()>y2)setLocation(getX(),getY()-10);
                    else if(getY()<y2)setLocation(getX(),getY()+10);
                    
                }
                else {
                    if(getX()>xgelen)setLocation(getX()-13,getY());
                    else if(getX()<xgelen)setLocation(getX()+13,getY());
                    if(getY()<ygelen)setLocation(getX(),getY()+10);
                    else if(getY()>ygelen)setLocation(getX(),getY()-10);
                }
                //z++;
                }
            });

        this.setLocation(dim.width/2-this.getSize().width/2 , dim.height/2-this.getSize().height/2);
        xgelen=dim.width/2-this.getSize().width/2;
        ygelen=dim.height/2-this.getSize().height/2;
    }
int x2=0;int y2=0;
    void formugoster(int gelx,int gely,int gelwidth,int gelheight){
setVisible(true);/*        
        x2=gelx;y2=gely;
        if(!isVisible()){
        setLocation(gelx, gely);
            setVisible(true);
    kapat=false;tm.start();
        }*/
    }
    
    void formukapat(){
        setVisible(false);
    /*if(isVisible()&&timeracik==false){
        kapat=true;tm.start();timeracik=true;}
    }*/
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        CncFaults = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        CncFaults.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CncFaults.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        CncFaults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CncFaultsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(CncFaults, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(CncFaults, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CncFaultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CncFaultsMouseClicked
        // TODO add your handling code here:
        
        ShowMesajFoto(CncFaults.getSelectedValue());
    }//GEN-LAST:event_CncFaultsMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        ajanframe.hatayiac=false;
        formukapat();
        
    }//GEN-LAST:event_formWindowClosing

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        // TODO add your handling code here:
        if(getY()+10>=ygelen&&getX()-10<=xgelen&&kapat==false){
            tm.stop();timeracik=false;
        }
        else if(getY()-10<y2&&getX()+10>=x2&&kapat==true){
            
    tm.stop();
            setVisible(false);
    ajanframe.hatayiac=false;
    timeracik=false;
//timeracik=false;
}

    }//GEN-LAST:event_formComponentMoved

    

    
    
    HataFotolari AjanHataFrame=new HataFotolari();
    public void ShowMesajFoto(String mesaj){

    //AjanHataFrame(new EmptyBorder(5, 5, 5, 5));
//    AjanHataFrame.setUndecorated(true);
  AjanHataFrame.etiketyaz(mesaj);
  AjanHataFrame.getContentPane().setBackground( Color.white );
   AjanHataFrame.show();
   
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hatalar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hatalar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hatalar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hatalar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hatalar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList<String> CncFaults;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
