/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajan;

import static ajan.AjanCutCharts.jTabbedPane1;
import static ajan.ajanframe.AjanCutParam;
import static ajan.ajanframe.AjanMachine;
import static ajan.ajanframe.AjanPortIn;
import static ajan.ajanframe.bundle;
import static ajan.ajanframe.localeDil;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.awt.Window;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author arge
 */
public class PurgeFrame extends javax.swing.JFrame {

    /**
     * Creates new form PurgeFrame
     */
    public PurgeFrame() {
        initComponents();
        CutPlasmaGasTLCheckBox.setText(AjanCutParam.Plasma.CutPlasmaGas);
        CutPlasmaGasTRCheckBox.setText(AjanCutParam.Plasma.CutPlasmaGas);//= new javax.swing.JCheckBox();
        CutShieldGasTLCheckBox.setText(AjanCutParam.Plasma.CutShieldGas);// = new javax.swing.JCheckBox();
        CutShieldGasTRCheckBox.setText(AjanCutParam.Plasma.CutShieldGas);
        
        PrePlasmaGasTRCheckBox.setText(AjanCutParam.Plasma.PrePlasmaGas);// = new javax.swing.JCheckBox();
        PrePlasmaGasTLCheckBox.setText(AjanCutParam.Plasma.PrePlasmaGas);// = new javax.swing.JCheckBox();
        PreShieldGasTRCheckBox.setText(AjanCutParam.Plasma.PreShieldGas);// = new javax.swing.JCheckBox();
        PreShieldGasTLCheckBox.setText(AjanCutParam.Plasma.PreShieldGas);// = new javax.swing.JCheckBox();               
        PreFlowProgress.setValue(0);
        CutFlowProgress.setValue(0);
        
        KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
            manager.addKeyEventDispatcher(new MyDispatcher());
//jProgressBar2 = new javax.swing.JProgressBar();


    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CutPlasmaGasTLCheckBox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        CutPlasmaGasTRCheckBox = new javax.swing.JCheckBox();
        PrePlasmaGasTRCheckBox = new javax.swing.JCheckBox();
        CutFlowProgress = new javax.swing.JProgressBar();
        PrePlasmaGasTLCheckBox = new javax.swing.JCheckBox();
        PreShieldGasTRCheckBox = new javax.swing.JCheckBox();
        PlasmaGasTRLabel = new javax.swing.JLabel();
        PreShieldGasTLCheckBox = new javax.swing.JCheckBox();
        CutShieldGasTLCheckBox = new javax.swing.JCheckBox();
        CutShieldGasTRCheckBox = new javax.swing.JCheckBox();
        PurgeLabel = new javax.swing.JLabel();
        ShieldGasTRLabel = new javax.swing.JLabel();
        PreFlowProgress = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        PlasmaGasTLLabel = new javax.swing.JLabel();
        ShieldGasTLLabel = new javax.swing.JLabel();
        PurgeErrorGas1 = new javax.swing.JLabel();
        PurgeErrorGas2 = new javax.swing.JLabel();
        PurgeErrorGas3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setAlwaysOnTop(true);
        setBackground(java.awt.SystemColor.activeCaptionBorder);
        setForeground(java.awt.Color.pink);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 239, 180));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        CutPlasmaGasTLCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CutPlasmaGasTLCheckBox.setText("jCheckBox1");

        jLabel8.setText("CutFlow");

        CutPlasmaGasTRCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CutPlasmaGasTRCheckBox.setText("jCheckBox1");

        PrePlasmaGasTRCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PrePlasmaGasTRCheckBox.setText("jCheckBox1");

        CutFlowProgress.setMaximum(24000);

        PrePlasmaGasTLCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PrePlasmaGasTLCheckBox.setText("jCheckBox1");

        PreShieldGasTRCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PreShieldGasTRCheckBox.setText("jCheckBox1");

        PlasmaGasTRLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PlasmaGasTRLabel.setText("Plasma Gas TR");

        PreShieldGasTLCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PreShieldGasTLCheckBox.setText("jCheckBox1");
        PreShieldGasTLCheckBox.setBorderPaintedFlat(true);
        PreShieldGasTLCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreShieldGasTLCheckBoxActionPerformed(evt);
            }
        });

        CutShieldGasTLCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CutShieldGasTLCheckBox.setText("jCheckBox1");
        CutShieldGasTLCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CutShieldGasTLCheckBoxActionPerformed(evt);
            }
        });

        CutShieldGasTRCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CutShieldGasTRCheckBox.setText("jCheckBox1");

        PurgeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PurgeLabel.setText("Purge Plasma Testing  Pressure 6 Bar");

        ShieldGasTRLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ShieldGasTRLabel.setText("Shield Gas TR");

        PreFlowProgress.setMaximum(24000);

        jLabel3.setText("PreFlow");

        PlasmaGasTLLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PlasmaGasTLLabel.setText("Plasma Gas TL");

        ShieldGasTLLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ShieldGasTLLabel.setText("Shield Gas TL");

        PurgeErrorGas1.setBackground(new java.awt.Color(255, 51, 204));
        PurgeErrorGas1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PurgeErrorGas1.setForeground(new java.awt.Color(153, 0, 153));

        PurgeErrorGas2.setBackground(new java.awt.Color(153, 0, 255));
        PurgeErrorGas2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PurgeErrorGas2.setForeground(new java.awt.Color(153, 0, 153));

        PurgeErrorGas3.setBackground(new java.awt.Color(204, 0, 204));
        PurgeErrorGas3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PurgeErrorGas3.setForeground(new java.awt.Color(102, 0, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PurgeLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(PreFlowProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(CutFlowProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(CutShieldGasTLCheckBox)
                                    .addComponent(PreShieldGasTLCheckBox)
                                    .addComponent(ShieldGasTLLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(PlasmaGasTLLabel)
                                    .addComponent(PrePlasmaGasTLCheckBox)
                                    .addComponent(CutPlasmaGasTLCheckBox))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(PreShieldGasTRCheckBox)
                                    .addComponent(CutShieldGasTRCheckBox)
                                    .addComponent(ShieldGasTRLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(PlasmaGasTRLabel)
                                    .addComponent(PrePlasmaGasTRCheckBox)
                                    .addComponent(CutPlasmaGasTRCheckBox)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PurgeErrorGas2)
                            .addComponent(PurgeErrorGas1)
                            .addComponent(PurgeErrorGas3))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PurgeLabel)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShieldGasTLLabel)
                    .addComponent(PlasmaGasTLLabel)
                    .addComponent(ShieldGasTRLabel)
                    .addComponent(PlasmaGasTRLabel))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreFlowProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreShieldGasTLCheckBox)
                    .addComponent(PrePlasmaGasTLCheckBox)
                    .addComponent(PreShieldGasTRCheckBox)
                    .addComponent(PrePlasmaGasTRCheckBox))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CutFlowProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CutShieldGasTLCheckBox)
                    .addComponent(CutPlasmaGasTLCheckBox)
                    .addComponent(CutShieldGasTRCheckBox)
                    .addComponent(CutPlasmaGasTRCheckBox))
                .addGap(18, 18, 18)
                .addComponent(PurgeErrorGas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PurgeErrorGas2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PurgeErrorGas3)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CutShieldGasTLCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CutShieldGasTLCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CutShieldGasTLCheckBoxActionPerformed

    private void PreShieldGasTLCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreShieldGasTLCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreShieldGasTLCheckBoxActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
          if(!AjanPortIn.stat.PurgeOn){dispose();}
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
  if (AjanMachine.Language == 0) localeDil = new Locale("en", "US");
        else if (AjanMachine.Language == 1) localeDil = new Locale("tr", "TR");
        else if (AjanMachine.Language == 2) localeDil = new Locale("pl", "PL");
        bundle = ResourceBundle.getBundle("ajan/diller/ajanframe",localeDil);
        changeLocale();

    }//GEN-LAST:event_formWindowActivated

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jPanel1KeyPressed
  
    private class MyDispatcher implements KeyEventDispatcher 
    {
       @Override//com.sun.glass.events.        
       public boolean dispatchKeyEvent(java.awt.event.KeyEvent e) 
       {
           if (isActive()) 
           {
                    if (e.getID() == java.awt.event.KeyEvent.KEY_PRESSED&& AjanPortIn.stat.PurgeOn==false) 
                    {
                        if(e.getKeyCode()==com.sun.glass.events.KeyEvent.VK_ESCAPE){dispose();}
                    }
            }
           return false;
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurgeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurgeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurgeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurgeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurgeFrame().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar CutFlowProgress;
    public javax.swing.JCheckBox CutPlasmaGasTLCheckBox;
    public javax.swing.JCheckBox CutPlasmaGasTRCheckBox;
    public javax.swing.JCheckBox CutShieldGasTLCheckBox;
    public javax.swing.JCheckBox CutShieldGasTRCheckBox;
    private javax.swing.JLabel PlasmaGasTLLabel;
    private javax.swing.JLabel PlasmaGasTRLabel;
    public javax.swing.JProgressBar PreFlowProgress;
    public javax.swing.JCheckBox PrePlasmaGasTLCheckBox;
    public javax.swing.JCheckBox PrePlasmaGasTRCheckBox;
    public javax.swing.JCheckBox PreShieldGasTLCheckBox;
    public javax.swing.JCheckBox PreShieldGasTRCheckBox;
    public javax.swing.JLabel PurgeErrorGas1;
    public javax.swing.JLabel PurgeErrorGas2;
    public javax.swing.JLabel PurgeErrorGas3;
    private javax.swing.JLabel PurgeLabel;
    private javax.swing.JLabel ShieldGasTLLabel;
    private javax.swing.JLabel ShieldGasTRLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

public void changeLocale() {


ShieldGasTLLabel.setText(bundle.getString("purge.ShieldGasTLLabel"));
PlasmaGasTLLabel.setText(bundle.getString("purge.PlasmaGasTLLabel"));
ShieldGasTRLabel.setText(bundle.getString("purge.ShieldGasTRLabel"));
PlasmaGasTRLabel.setText(bundle.getString("purge.PlasmaGasTRLabel"));
PurgeLabel.setText(bundle.getString("purge.PurgeLabel"));

    
}


}
