/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajan;

/**
 *
 * @author ajanuser
 */
import static ajan.ajanframe.dxfVectWithOff;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;
public class SelectToolbarFrame extends javax.swing.JFrame {
    
    private static final int TIME = 200;
    private static final int MILLIS_PER_FRAME = 33;
    private static final float DELTA = MILLIS_PER_FRAME / (float)TIME; //how much the opacity will change on each tick


    /**
     * Creates new form SelectToolbarFrame
     */
    public SelectToolbarFrame() {
        initComponents();
        boolean in=true;
            this.setOpacity(in ? 0f : 1f); //if we're fading in, make sure our opacity is 0, and 1 if we're fading out
        if (in) //set the state back to normal because we might have been minimized
            this.setState(JFrame.NORMAL); 
        final Timer timer = new Timer();
        TimerTask timerTask = new TimerTask()
        {
            float opacity = in ? 0f : 1f;
            float delta = in ? DELTA : -DELTA;

            @Override
            public void run()
            {
                opacity += delta; //tweak the opacity
                if (opacity < 0) //we're invisible now
                {
                    setState(JFrame.ICONIFIED); //hide this
                    setOpacity(1f); //then make it opaque again, so it'll reappear properly if they click the taskbar 
                    timer.cancel(); //stop the timer
                }
                else if (opacity > 1) //we're fully visible now
                {
                    setOpacity(1f); //make the opacity an even 1.0f
                    timer.cancel(); //stop the timer
                }
                else
                    setOpacity(opacity);
            }
        };
        timer.scheduleAtFixedRate(timerTask, MILLIS_PER_FRAME, MILLIS_PER_FRAME);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        buton3 = new javax.swing.JToggleButton();
        buton2 = new javax.swing.JToggleButton();
        buton1 = new javax.swing.JToggleButton();
        textbox1 = new javax.swing.JTextField();
        kapatbuton = new ajan.FahriButon();
        jLabel4 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(buton3);
        buton3.setText("jToggleButton3");
        buton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(buton2);
        buton2.setText("jToggleButton2");
        buton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(buton1);
        buton1.setText("jToggleButton1");
        buton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton1ActionPerformed(evt);
            }
        });

        textbox1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        textbox1.setForeground(new java.awt.Color(102, 102, 102));
        textbox1.setText("jTextField1");
        textbox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textbox1MouseClicked(evt);
            }
        });
        textbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox1ActionPerformed(evt);
            }
        });
        textbox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textbox1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textbox1KeyReleased(evt);
            }
        });

        kapatbuton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kapatbutonMouseClicked(evt);
            }
        });
        kapatbuton.tiklanabilir=false;

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajanimages/icons8_close_window_30px.png"))); // NOI18N

        javax.swing.GroupLayout kapatbutonLayout = new javax.swing.GroupLayout(kapatbuton);
        kapatbuton.setLayout(kapatbutonLayout);
        kapatbutonLayout.setHorizontalGroup(
            kapatbutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kapatbutonLayout.setVerticalGroup(
            kapatbutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        label1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(102, 102, 102));
        label1.setText("Offset Value:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(textbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kapatbuton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buton2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
            .addComponent(buton3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
            .addComponent(kapatbuton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(textbox1)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buton1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        buton_etiketle();
        
    }//GEN-LAST:event_formWindowActivated

    private void buton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton1ActionPerformed
        // TODO add your handling code here:
        if(Graph.GrFunc.StartSelectEnable==true||Graph.GrFunc.EndSelectEnable==true){
                Graph.GrFunc.reset();
        Graph.GrFunc.StartSelectEnable=true;
       }
       else if(Graph.GrFunc.DryRunEnable==true||Graph.GrFunc.DryRunStartEnable==true||Graph.GrFunc.DryRunPauseEnable==true)
        {
            Graph.canvas1.repaint();
        Graph.GrFunc.DryRunEnable=true;
        Graph.GrFunc.DryRunStartEnable=true;
        Graph.GrFunc.DryRunPauseEnable=false;     
        }
        else if(Graph.GrFunc.ExTrimEnable==true||Graph.GrFunc.ReverseEnable==true||Graph.GrFunc.MarkerEnable==true||Graph.GrFunc.OffsetEnable==true||Graph.GrFunc.PipeCutEnable==true||Graph.GrFunc.PiercingAngle==true)
        {
           textbox1ActionPerformed(null);
            Graph.GrFunc.SelectAll=false;
        }
        
        
        
        
        
    }//GEN-LAST:event_buton1ActionPerformed

    private void buton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton2ActionPerformed
        // TODO add your handling code here:
         if(Graph.GrFunc.StartSelectEnable==true||Graph.GrFunc.EndSelectEnable==true){
        Graph.GrFunc.reset();
        Graph.GrFunc.EndSelectEnable=true;
       }
         else if(Graph.GrFunc.DryRunEnable==true||Graph.GrFunc.DryRunStartEnable==true||Graph.GrFunc.DryRunPauseEnable==true)
        {
                    Graph.GrFunc.DryRunPauseEnable=!Graph.GrFunc.DryRunPauseEnable;     
        }
        if(Graph.GrFunc.OffsetEnable==true||Graph.GrFunc.ReverseEnable==true||Graph.GrFunc.MarkerEnable==true||Graph.GrFunc.PipeCutEnable==true||Graph.GrFunc.ExTrimEnable==true||Graph.GrFunc.PiercingAngle==true)
        {
            textbox1ActionPerformed(null);
            Graph.GrFunc.SelectAll=true;
            if(Graph.GrFunc.OffsetEnable)    Graph.GrFunc.OffsetApply=true;//rev99
            this.setFocusableWindowState(false);
            Graph.canvas1.repaint();
            this.dispose();
        }
        
    }//GEN-LAST:event_buton2ActionPerformed

    private void buton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton3ActionPerformed
        // TODO add your handling code here:
        if(Graph.GrFunc.StartSelectEnable==true||Graph.GrFunc.EndSelectEnable==true){
        Graph.GrFunc.reset();
        Graph.CutStartObjNo=0;Graph.CutEndObjNo=dxfVectWithOff.size();
        Graph.secimleriptal();
        }
    else if(Graph.GrFunc.DryRunEnable==true||Graph.GrFunc.DryRunStartEnable==true||Graph.GrFunc.DryRunPauseEnable==true)
    {
   Graph.GrFunc.DryRunStartEnable=false;
    Graph.GrFunc.DryRunPauseEnable=false;

    }
        
        else if(Graph.GrFunc.OffsetEnable==true||Graph.GrFunc.OffsetApply==true||Graph.GrFunc.PiercingAngle==true)
        {
           // Graph.GrFunc.reset();
            textbox1ActionPerformed(null);
            Graph.GrFunc.OffsetApply=true;
            this.setFocusableWindowState(false);
            Graph.canvas1.repaint();
            buton1.requestFocus();
        }
        
        if(Graph.GrFunc.ExTrimEnable==true)
        {
        Graph.reverse=buton3.isSelected();//isEnabled();
        }
    }//GEN-LAST:event_buton3ActionPerformed

    private float degeral_float(String str) {
            str=str.replace(",", ".");
        //return Float.valueOf(str.replaceAll("[^\\d.]+-|\\.(?!\\d)", ""));
        return Float.valueOf(str.replaceAll("[^0-9?!\\\\.]", ""));
        
        //return Float.parseFloat(str);
    }
        private int degeral_int(String str) {
        return Integer.parseInt(str.replaceAll("\\D+",""));
    }
        
    private void textbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox1ActionPerformed
        // TODO add your handling code here:
        if(Graph.GrFunc.PiercingAngle==false){
        if(ajanframe.AjanMachine.MachineType==0) { 
            ajanframe.AjanCutParam.Plasma.KerfWidth=(degeral_float(textbox1.getText())*2)*ajanframe.IncCarpan;
        textbox1.setText(String.format(ajanframe.FormatMetricInc,(ajanframe.AjanCutParam.Plasma.KerfWidth/2.)/ajanframe.IncCarpan)+ ajanframe.MetricIncBirim);
        }
        else  {    ajanframe.AjanCutParam.Oxy.KerfWidth=(degeral_float(textbox1.getText())*2)*ajanframe.IncCarpan;textbox1.setText(String.format(ajanframe.FormatMetricInc,(ajanframe.AjanCutParam.Oxy.KerfWidth/2)/ajanframe.IncCarpan)+ ajanframe.MetricIncBirim);}
        }else if(Graph.GrFunc.PiercingAngle==true){
        Graph.piercingangle=Float.parseFloat(textbox1.getText());
        }
        this.setFocusableWindowState(false);
    }//GEN-LAST:event_textbox1ActionPerformed

    private void textbox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textbox1KeyPressed
        // TODO add your handling code here:
    this.setFocusableWindowState(true);
    textbox1.requestFocus();
    }//GEN-LAST:event_textbox1KeyPressed

    private void textbox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textbox1MouseClicked
        // TODO add your handling code here:
            this.setFocusableWindowState(true);
    textbox1.requestFocus();
    }//GEN-LAST:event_textbox1MouseClicked

    private void textbox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textbox1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_textbox1KeyReleased

    private void kapatbutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatbutonMouseClicked
        // TODO add your handling code here:
         Graph.GrFunc.reset();
         Graph.islembitti=true;
         dispose();
      //  kaybol();
    }//GEN-LAST:event_kapatbutonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectToolbarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectToolbarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectToolbarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectToolbarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectToolbarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buton1;
    private javax.swing.JToggleButton buton2;
    private javax.swing.JToggleButton buton3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private ajan.FahriButon kapatbuton;
    private javax.swing.JLabel label1;
    private javax.swing.JTextField textbox1;
    // End of variables declaration//GEN-END:variables

    private void buton_etiketle() {

        if(Graph.GrFunc.StartSelectEnable==true||Graph.GrFunc.EndSelectEnable==true)
        {buttonGroup1.add(buton3);
            buton1.setText(ajanframe.bundle.getString("Select.CutStart"));buton1.setSelected(true);
            buton2.setText(ajanframe.bundle.getString("Select.CutEnd"));
            buton3.setVisible(true);buton3.setText(ajanframe.bundle.getString("Select.CutAll"));
            label1.setVisible(false);textbox1.setVisible(false);

            this.setSize(new java.awt.Dimension(buton1.getWidth()+buton2.getWidth()+buton3.getWidth()+kapatbuton.getWidth()+50,getHeight()));
            
        }
        else if(Graph.GrFunc.OffsetEnable==true||Graph.GrFunc.OffsetApply==true)
        {buttonGroup1.add(buton3);
            buton1.setText(ajanframe.bundle.getString("Select.SelectObjects"));buton1.setSelected(true);
            buton2.setText(ajanframe.bundle.getString("Select.ApplyAll"));
            buton3.setVisible(true);buton3.setText(ajanframe.bundle.getString("Select.Apply"));
            label1.setVisible(true);label1.setText(ajanframe.bundle.getString("Select.Offset"));
                    if(ajanframe.AjanMachine.MachineType==0)        textbox1.setText(String.format(ajanframe.FormatMetricInc,(ajanframe.AjanCutParam.Plasma.KerfWidth/2.)/ajanframe.IncCarpan)+ajanframe.MetricIncBirim);
                    else textbox1.setText(String.format(ajanframe.FormatMetricInc,(ajanframe.AjanCutParam.Oxy.KerfWidth/2)/ajanframe.IncCarpan)+ajanframe.MetricIncBirim);
                    
                    
            this.setSize(new java.awt.Dimension(this.getWidth(),getHeight()));
        }
         else if(Graph.GrFunc.PiercingAngle==true)
        {buttonGroup1.add(buton3);
            buton1.setText(ajanframe.bundle.getString("Select.SelectObjects"));buton1.setSelected(true);
            buton2.setText(ajanframe.bundle.getString("Select.ApplyAll"));
            buton3.setVisible(true);buton3.setText(ajanframe.bundle.getString("Select.Apply"));
            label1.setVisible(true);label1.setText(ajanframe.bundle.getString("PiercingAngle")+" :");
                     textbox1.setText(String.format("%.2f",Graph.piercingangle));
                    
            this.setSize(new java.awt.Dimension(this.getWidth(),getHeight()));
        }
        else if(Graph.GrFunc.DryRunEnable==true||Graph.GrFunc.DryRunStartEnable==true||Graph.GrFunc.DryRunPauseEnable==true)
        {
            //buttonGroup1.add(buton3);
            buton1.setText("");buton1.setSelected(true);
            buton2.setText("");
            buton3.setVisible(true);buton3.setText("");
            label1.setVisible(false);textbox1.setVisible(false);
            /*
            SimulationRateSlider.setValue(SimulationRateSlider.getValue()-50);
            feedratelabel.setText(ajanframe.AjanCutParam.Plasma.CuttingSpeed*(SimulationRateSlider.getValue()/50)*1+" mm/dk");
            */
            
            
            buton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajanimages/newpackage/button/icons8_play_button_30px.png"))); // NOI18N
            buton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ajanimages/newpackage/button/icons8_play_button_30px.png")));
            buton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ajanimages/newpackage/button/icons8_play_button_30px.png")));
            buton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajanimages/newpackage/button/icons8_stop_squared_30px.png"))); // NOI18N
            buton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ajanimages/newpackage/button/icons8_stop_squared_30px.png")));
            buton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ajanimages/newpackage/button/icons8_stop_squared_30px.png")));
            buton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajanimages/newpackage/button/icons8_pause_squared_30px.png"))); // NOI18N
            buton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ajanimages/newpackage/button/icons8_pause_squared_30px.png")));
            buton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ajanimages/newpackage/button/icons8_pause_squared_30px.png")));

            this.setSize(new java.awt.Dimension(buton1.getWidth()+buton2.getWidth()+buton3.getWidth()+textbox1.getWidth()+label1.getWidth()+kapatbuton.getWidth(),getHeight()));
            
            
            
        }else if(Graph.GrFunc.MarkerEnable==true||Graph.GrFunc.ReverseEnable==true)
        {buttonGroup1.add(buton3);
            buton1.setText(ajanframe.bundle.getString("Select.SelectObjects"));buton1.setSelected(true);
        if(Graph.GrFunc.MarkerEnable==true)    buton2.setText(ajanframe.bundle.getString("Select.MarkAll"));
         else   buton2.setText("Select.ReverseAll");
            buton3.setVisible(false);//buton3.setText("<html><center>Cut ALL<br>Objects</html>");
            label1.setVisible(false);textbox1.setVisible(false);
            
            this.setSize(new java.awt.Dimension(buton1.getWidth()+buton2.getWidth()+kapatbuton.getWidth(),getHeight()));
            
        }else if(Graph.GrFunc.ExTrimEnable==true)
        {
            buton1.setText(ajanframe.bundle.getString("Select.SelectObjects"));buton1.setSelected(true);
            buton2.setText(ajanframe.bundle.getString("Select.AllSame"));
            buton3.setText(ajanframe.bundle.getString("Select.Reverse"));
            buton3.setVisible(true);//buton3.setText("<html><center>Cut ALL<br>Objects</html>");
            buttonGroup1.remove(buton3);
            label1.setVisible(false);textbox1.setVisible(false);
            
            this.setSize(new java.awt.Dimension(buton1.getWidth()+buton2.getWidth()+buton3.getWidth()+kapatbuton.getWidth()+50,getHeight()));
            buton3.setSelected(Graph.reverse);
        }else if(Graph.GrFunc.PipeCutEnable==true)
        {
            buton1.setText(ajanframe.bundle.getString("Select.SelectObjects"));buton1.setSelected(true);
            buton2.setText(ajanframe.bundle.getString("Select.PipeCutAll"));
            buton3.setVisible(false);//buton3.setText("<html><center>Cut ALL<br>Objects</html>");
            label1.setVisible(false);textbox1.setVisible(false);
            
            this.setSize(new java.awt.Dimension(buton1.getWidth()+buton2.getWidth()+textbox1.getWidth()+label1.getWidth()+kapatbuton.getWidth(),getHeight()));
            
        }
        
        
        
    }

    private void kaybol() {
    final Timer timer = new Timer();
        TimerTask timerTask = new TimerTask()
        {
            float opacity = 1f;
            float delta = DELTA;

            @Override
            public void run()
            {
                opacity -= delta; //tweak the opacity
                if (opacity < 0) //we're invisible now
                {
                    setState(JFrame.ICONIFIED); //hide this
                    setOpacity(0f); //then make it opaque again, so it'll reappear properly if they click the taskbar 
                    dispose();
                    timer.cancel(); //stop the timer
                }
                else if (opacity > 1) //we're fully visible now
                {
                    setOpacity(0f); //make the opacity an even 1.0f
                    dispose();
                    timer.cancel(); //stop the timer
                }
                else
                    setOpacity(opacity);
            }
        };
        timer.scheduleAtFixedRate(timerTask, MILLIS_PER_FRAME, MILLIS_PER_FRAME);
    }
}
