/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajan;

import static ajan.ajanframe.AjanMachine;

/**
 *
 * @author ajanuser
 */
public class ShowReferenceFrame extends javax.swing.JFrame {

    /**
     * Creates new form ShowReferenceFrame
     */
    public ShowReferenceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelZero1X = new javax.swing.JLabel();
        labelZero1Y = new javax.swing.JLabel();
        labelZero1Angle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setEnabled(false);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelZero1X.setFont(new java.awt.Font("Digital-7", 0, 30)); // NOI18N
        labelZero1X.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelZero1X.setText("X : 135.25 mm ");
        getContentPane().add(labelZero1X, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 15, -1, 30));

        labelZero1Y.setFont(new java.awt.Font("Digital-7", 0, 30)); // NOI18N
        labelZero1Y.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelZero1Y.setText("X : 135.25 mm ");
        getContentPane().add(labelZero1Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, 30));

        labelZero1Angle.setFont(new java.awt.Font("Digital-7", 0, 30)); // NOI18N
        labelZero1Angle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelZero1Angle.setText("X ANGLE : 1 ");
        getContentPane().add(labelZero1Angle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajanimages/referenceBack.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
               ReferanslarDb rd=new ReferanslarDb(AjanMachine.referenceID);
        labelZero1X.setText("X : " + String.format("%.2f mm", ((float) rd.getX() / 100)));
        labelZero1Y.setText("Y : " + String.format("%.2f mm", ((float) rd.getY() / 100)));        
        labelZero1Angle.setText("X Angle : " + String.format("%.2f", (rd.getXangle() * 180 / Math.PI)));//gecerliproje.PlateToXAxisAngle=Job.PlateToXAxisAngle;
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowReferenceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowReferenceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowReferenceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowReferenceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowReferenceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelZero1Angle;
    private javax.swing.JLabel labelZero1X;
    private javax.swing.JLabel labelZero1Y;
    // End of variables declaration//GEN-END:variables
}
