/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajan;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author fahri
 */
public class StatsFrame extends javax.swing.JFrame {

    /**
     * Creates new form StatsFrame
     */
    public StatsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tumKayitgrup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        takvimstart = new org.jdesktop.swingx.JXDatePicker();
        takvimend = new org.jdesktop.swingx.JXDatePicker();
        BaslamaTarihBundle = new javax.swing.JLabel();
        BitisTarihBundle = new javax.swing.JLabel();
        SorgulaButon = new javax.swing.JButton();
        radioTarih = new javax.swing.JRadioButton();
        radioTum = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        OperatorNameBundle = new javax.swing.JLabel();
        ComboOperator = new javax.swing.JComboBox<>();
        Login_btn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SonucTablosu = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ToplamTablosu = new javax.swing.JTable();
        PdfKaydetButton = new javax.swing.JButton();
        ClearAllButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        takvimstart.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        takvimend.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        BaslamaTarihBundle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BaslamaTarihBundle.setText("BAŞLAMA TARİHİ :");

        BitisTarihBundle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BitisTarihBundle.setText("BİTİŞ TARİHİ");

        SorgulaButon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SorgulaButon.setText("SORGULA");
        SorgulaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SorgulaButonActionPerformed(evt);
            }
        });

        tumKayitgrup.add(radioTarih);
        radioTarih.setText("TARİH ARALIĞI İLE SORGULA");

        tumKayitgrup.add(radioTum);
        radioTum.setSelected(true);
        radioTum.setText("TÜMÜNÜ GETİR");

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        OperatorNameBundle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OperatorNameBundle.setText("OPERATOR NAME");

        ComboOperator.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboOperator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboOperator.setEnabled(false);
        ComboOperator.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboOperatorİtemStateChanged(evt);
            }
        });
        ComboOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOperatorActionPerformed(evt);
            }
        });

        Login_btn.setText("LOGIN");
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });

        Logout_btn.setText("LOGOUT");
        Logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OperatorNameBundle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(Logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ComboOperator, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OperatorNameBundle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Login_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(Logout_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(177, 177, 177))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BaslamaTarihBundle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BitisTarihBundle, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(takvimstart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(takvimend, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(radioTum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioTarih)))
                .addGap(18, 18, 18)
                .addComponent(SorgulaButon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioTarih)
                            .addComponent(radioTum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(takvimstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BaslamaTarihBundle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(takvimend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BitisTarihBundle)))
                    .addComponent(SorgulaButon, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        SonucTablosu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SonucTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "WORK_ID","WORK DATE","OPERATOR NAME" ,"PROJECT NAME","WORK TIME","TOTAL PIERCE","TOTAL LENGHT"
            }
        )
        {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    SonucTablosu.removeColumn( SonucTablosu.getColumnModel().getColumn(0) );
    SonucTablosu.setRowHeight(25);
    SonucTablosu.setRowSelectionAllowed(false);
    SonucTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            SonucTablosuMouseClicked(evt);
        }
    });
    jScrollPane2.setViewportView(SonucTablosu);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2)
            .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
            .addContainerGap())
    );

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

    ToplamTablosu.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            " ", " ", " ", " "
        }
    ));
    ToplamTablosu.setRowHeight(25);
    jScrollPane3.setViewportView(ToplamTablosu);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane3)
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
            .addContainerGap())
    );

    PdfKaydetButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    PdfKaydetButton.setText("PDF KAYDET");
    PdfKaydetButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            PdfKaydetButtonActionPerformed(evt);
        }
    });

    ClearAllButton.setText("CLEAR ALL");
    ClearAllButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ClearAllButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ClearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PdfKaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(0, 0, 0))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(PdfKaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ClearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SorgulaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SorgulaButonActionPerformed
        // TODO add your handling code here:
        TabloYenile = true;
        changeLocale();

        ajanframe.statrecord.getTumKayit(SonucTablosu, ToplamTablosu, new java.sql.Timestamp(takvimstart.getDate().getTime()), new java.sql.Timestamp(takvimend.getDate().getTime()), radioTum.isSelected());


    }//GEN-LAST:event_SorgulaButonActionPerformed

    public void setTakvim(Date takvim) {
        SimpleDateFormat df = new SimpleDateFormat("dd.MMMM.yyyy");
        takvimstart.setFormats(df);
        takvimend.setFormats(df);
        takvimstart.setDate(takvim);
        takvimend.setDate(takvimstart.getDate());

    }

    public void ComboRefresh() {
        ComboOperator.removeAllItems();
        for (int i = 0; i < ajanframe.statrecord.OperatorNames.size(); i++) {
            ComboOperator.addItem(ajanframe.statrecord.OperatorNames.get(i).toString());
        }
        for (int i = 0; i < ComboOperator.getItemCount(); i++) {
            if (ComboOperator.getItemAt(i).compareTo(ajanframe.statrecord.getOperatorName()) == 0) {
                ComboOperator.setSelectedIndex(i);
                break;
            }
        }
    }


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DataGiris = 0;
        ComboRefresh();
        //operator_name_lbl.setText(ajanframe.statrecord.getOperatorName());
        DataGiris = 1;
        if (ComboOperator.getItemAt(ComboOperator.getSelectedIndex()).toString().equals("Not Selected")) {
            Login_btn.setEnabled(true);
            Logout_btn.setEnabled(false);
        } else {
            Login_btn.setEnabled(false);
            Logout_btn.setEnabled(true);
        }

    }//GEN-LAST:event_formWindowOpened

    private void PdfKaydetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PdfKaydetButtonActionPerformed
        // TODO add your handling code here:
        if (SonucTablosu.getRowCount() > 1) {
            File pdfKayit = new File("pdfreport.pdf");
            javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();

            //chooser.setCurrentDirectory(new File("/home/me/Documents"));
            chooser.setCurrentDirectory(new File(ajanframe.userDir));
            FileNameExtensionFilter ajnfilter = new FileNameExtensionFilter(
                    "report files (*.pdf)", "pdf");
            chooser.setFileFilter(ajnfilter);
            int retrival = chooser.showSaveDialog(null);
            if (retrival == javax.swing.JFileChooser.APPROVE_OPTION) {

                if (chooser.getSelectedFile().getAbsolutePath().toLowerCase().endsWith(".pdf")) {
                    pdfKayit = chooser.getSelectedFile();
                } else {
                    pdfKayit = new File(chooser.getSelectedFile() + ".pdf");
                }

            }
            ajanframe.statrecord.SavePdf(SonucTablosu, pdfKayit);

        }
    }//GEN-LAST:event_PdfKaydetButtonActionPerformed

    private void ClearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAllButtonActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;//rev14
        int dialogResult = JOptionPane.showConfirmDialog(this, "Bütün Kayıtlar Silinecek.\n" + ajanframe.bundle.getString("Eminmisin"), "Warning", dialogButton);//degree alt+248
        if (dialogResult == 0) {

            SonucTablosu.setModel(new DefaultTableModel());
            ajanframe.statrecord.clearAll();

        }

    }//GEN-LAST:event_ClearAllButtonActionPerformed

    private void SonucTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SonucTablosuMouseClicked
        // TODO add your handling code here:
        int indexNo = 0;
        if (evt.getClickCount() == 2) {

            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            indexNo = Integer.parseInt(SonucTablosu.getModel().getValueAt(SonucTablosu.getSelectedRow(), 0).toString());
            StatsDetailFrame detailframe = new StatsDetailFrame();
            detailframe.setIndexNo(indexNo);
            detailframe.setLocation(dim.width / 2 - detailframe.getSize().width / 2, dim.height / 2 - detailframe.getSize().height / 2);
            detailframe.show();

        }
    }//GEN-LAST:event_SonucTablosuMouseClicked
    public static String gelenDeger = null;
    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
        // TODO add your handling code here:
        TabloYenile = false;
//DialogAxesInputFrame dfr=new DialogAxesInputFrame(ajanframe.bundle.getString("OperatorEkle"),"",Color.getHSBColor(240,240, 240));
        AddOperatorFrame dfr = new AddOperatorFrame();

        dfr.setLocation(jPanel5.getX() + Login_btn.getLocation().x + this.getX() + 10, jPanel5.getY() + this.getY() + Login_btn.getLocation().y + (Login_btn.getHeight() + 30));
        dfr.setModal(true);
        dfr.show();

        /*
if(gelenDeger!=null)
{
    String s = gelenDeger;
    if(ajanframe.statrecord.addOperator(gelenDeger)==true){
    DataGiris=0;
            ComboRefresh();
               DataGiris=1;
    }
}
         */
        DataGiris = 0;
        ComboRefresh();
        DataGiris = 1;
        if (ComboOperator.getItemAt(ComboOperator.getSelectedIndex()).toString().equals("Not Selected")) {
            Login_btn.setEnabled(true);
            Logout_btn.setEnabled(false);
        } else {
            Login_btn.setEnabled(false);
            Logout_btn.setEnabled(true);
        }
    }//GEN-LAST:event_Login_btnActionPerformed
    static int DataGiris = 0;
    private void ComboOperatorİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboOperatorİtemStateChanged
        // TODO add your handling code here:
        if (DataGiris == 0) {
            return;
        }
        DataGiris = 0;

        if (ComboOperator.getItemCount() > 0) {
            if (ajanframe.statrecord.OperatorSec(ComboOperator.getItemAt(ComboOperator.getSelectedIndex()).toString()) == true) {
                DataGiris = 0;
                ComboRefresh();
                DataGiris = 1;
            }
        }

        DataGiris = 1;
    }//GEN-LAST:event_ComboOperatorİtemStateChanged

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;//rev14
        int dialogResult = JOptionPane.showConfirmDialog(this, /*ajanframe.bundle.getString("Eminmisin")*/"Are You Sure?", "Warning", dialogButton);//degree alt+248
        if (dialogResult == 0) {
            ajanframe.statrecord.OperatorSec("Not Selected");
            DataGiris=0;
            ComboRefresh();
               DataGiris=1;
               if (ComboOperator.getItemAt(ComboOperator.getSelectedIndex()).toString().equals("Not Selected")) {
            Login_btn.setEnabled(true);
            Logout_btn.setEnabled(false);
        } else {
            Login_btn.setEnabled(false);
            Logout_btn.setEnabled(true);
        }
            /* 
         if(ajanframe.statrecord.OperatorSil(ComboOperator.getItemAt(ComboOperator.getSelectedIndex()).toString())==true){    
               DataGiris=0;
            ComboRefresh();
               DataGiris=1;
        }*/
        }
    }//GEN-LAST:event_Logout_btnActionPerformed

    private void ComboOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOperatorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboOperatorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        changeLocale();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BaslamaTarihBundle;
    private javax.swing.JLabel BitisTarihBundle;
    private javax.swing.JButton ClearAllButton;
    private javax.swing.JComboBox<String> ComboOperator;
    private javax.swing.JButton Login_btn;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JLabel OperatorNameBundle;
    private javax.swing.JButton PdfKaydetButton;
    private javax.swing.JTable SonucTablosu;
    private javax.swing.JButton SorgulaButon;
    private javax.swing.JTable ToplamTablosu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton radioTarih;
    private javax.swing.JRadioButton radioTum;
    private org.jdesktop.swingx.JXDatePicker takvimend;
    private org.jdesktop.swingx.JXDatePicker takvimstart;
    private javax.swing.ButtonGroup tumKayitgrup;
    // End of variables declaration//GEN-END:variables
boolean TabloYenile = true;

    public void changeLocale() {

        BaslamaTarihBundle.setText(ajanframe.bundle.getString("BaslamaTarih"));
        BitisTarihBundle.setText(ajanframe.bundle.getString("BitisTarih"));
        radioTum.setText(ajanframe.bundle.getString("TumKayitlar"));
        radioTarih.setText(ajanframe.bundle.getString("TarihAraligi"));
        SorgulaButon.setText(ajanframe.bundle.getString("Sorgula"));

        /*if (ComboOperator.getItemAt(ComboOperator.getSelectedIndex()).toString().equals("Not Selected")) {
        Login_btn.setText(ajanframe.bundle.getString("OperatorEkle"));
        Logout_btn.setText(ajanframe.bundle.getString("OperatorSil"));*/


        ClearAllButton.setText(ajanframe.bundle.getString("ClearAll"));

        PdfKaydetButton.setText(ajanframe.bundle.getString("KaydetButton") + " PDF ");
        if (TabloYenile == true) {
            TabloYenile = false;
            SonucTablosu.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                    },
                    new String[]{
                        "WORK_ID", ajanframe.bundle.getString("ProjectDate"), ajanframe.bundle.getString("OperatorName"), ajanframe.bundle.getString("ProjectButton_name"), ajanframe.bundle.getString("EllapsedTime")
                    }
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            }
            );
            SonucTablosu.removeColumn(SonucTablosu.getColumnModel().getColumn(0));
        }

    }

}
