/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajan;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;

/**
 *
 * @author cnc
 */
public class Version extends javax.swing.JFrame {

    /**
     * Creates new form Version
     */
    public Version() {
        initComponents();
      //jLabel2.setText("Version : "+ajanframe.VersionNumber);
      //Version 1.0.1.2   28 ARALIK 2017 // PlazmaKesmiyor hatası infromcnc ye alindi
                                         // Elkumandada FAST tuşu basılı kalmıyor
      //jLabel2.setText("Version : 1.0.1.2");//Basinc hatalari okunuyor.
      //jLabel2.setText("Version : 1.0.1.3");//Pipe Cut Eklendi
      //jLabel2.setText("Version : 1.0.0.4");//Pipe Cut Eklendi + Resume duzeltildi
      //jLabel2.setText("Version : 1.0.0.5");//Pipe Cut Eklendi + XY XA DUZLEMİ
      //jLabel2.setText("Version : 1.0.0.6");//18 OCAK 2018 pipecut resume düzenleme
      //jLabel2.setText("Version : 1.0.0.7");//19 OCAK 2018 pipecut resume düzenleme 
      //jLabel2.setText("Version : 1.0.0.8");//19 OCAK 2018 Xaxis aposler ile yapıldı
      //jLabel2.setText("Version : 1.0.0.9");//22 OCAK 2018 thc on keserken elkumandadan yukarı kalkmıyordu
                                            // resume ateşledikten hemen sonra pause abort yapınca resume yapmıyordu. düzeltildi.
        //jLabel2.setText("Version : 1.0.0.10");//23 OCAK 2018 Graph PipeCut butonu düzenlendi
        //jLabel2.setText("Version : 1.0.0.11");//23 OCAK 2018 Graph PipeCut kit eklendi sadece 2 tane haluk beye verildi
        //jLabel2.setText("Version : 1.0.0.12");//30 OCAK 2018 rev 1-2-3-4 yapıldı
        //jLabel2.setText("Version : 1.0.0.13");//30 OCAK 2018 rev 1-2-3-4 yapıldı
        //jLabel2.setText("Version : 1.0.0.14");//22 SUBAT 2018 5 eksen calismasi öncesi
        //jLabel2.setText("Version : 1.0.0.15");//rev9 eklendi 26 subat 2018
        //jLabel2.setText("Version : 1.0.0.16");//rev10 eklendi 07 Mart 2018
        //jLabel2.setText("Version : 1.0.0.17");//INCH EKLENDI
        //jLabel2.setText("Version : 2.0");//BEVELCUT EKLENDI
        //jLabel2.setText("Version : 2.1");//Kesim Geçmişi Tutma eklendi.rev12 eklendi
        //jLabel2.setText("Version : 2.2");//rev13 REv14
        //jLabel2.setText("Version : 2.2.1");//rev15
        //jLabel2.setText("Version : 2.2.2");//rev16
        //jLabel2.setText("Version : 2.2.3");//rev17 Essi alma düzenlendi inchte gereksiz kontur geliyo ajancamden
        //jLabel2.setText("Version : 2.5.1");//rev18 MDI dan H1(HS)  H2(HC) modlari eklendi
        //jLabel2.setText("Version : 2.6");//rev21
        //jLabel2.setText("Version : 2.6.2");//400ampFlag düzeltme
        //jLabel2.setText("Version : 2.6.3");//Pipecut arc x ekseninde problem vardı düzeltildi
        //jLabel2.setText("Version : 2.6.4");//array command eklendi
        //jLabel2.setText("Version : 2.6.7");//bevel son kontur kayboluyordu
        //jLabel2.setText("Version : 2.6.8");//oksijen gaz hatalari duzeltildi
        //jLabel2.setText("Version : 2.6.9");//C ve D ekseni resposc düzeltildi
        //jLabel2.setText("Version : 2.6.11");//C ve D ekseni resposc düzeltildi
        //jLabel2.setText("Version : 2.6.12");//rev24
        //jLabel2.setText("Version : 2.6.13");//rev25
        //jLabel2.setText("Version : 2.2018.11.14");//rev24
        //jLabel2.setText("Version : 3.2018.12.28");//rev25
        //jLabel2.setText("Version : 3.27 - 29.01.2019");//rev27
        //jLabel2.setText("Version : 3.28 - 12.03.2019");//rev27
          jLabel2.setText("Version : 3.29 - 03.05.2019");//rev27
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        panel2 = new java.awt.Panel();

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(775, 550));
        setSize(new java.awt.Dimension(499, 450));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 102));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AJAN ELECTRONIC PLASMA & OXY CONTROLLER");

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Version 2017 - 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addGap(309, 309, 309))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_1.jpg"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(750, 750));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 90, 490, 230);

        panel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setText("Telefon: 0 232 328 12 02");

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel5.setText("Faks: 0 232 328 15 01 ");

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel6.setText(" Teknik Destek: 444 25 26");

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel7.setText(" AJAN ELEKTRONİK SAN. VE TİC. LTD. ŞTİ.  10039 SOK. NO:10 AOSB MAH. 35620 ÇİĞLİ/İZMİR");

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel8.setText(" Web: www.ajancnc.com");

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel9.setText("Mail: info@ajancnc.com ");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(54, 54, 54))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        getContentPane().add(panel1);
        panel1.setBounds(0, 320, 770, 210);

        panel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        getContentPane().add(panel3);
        panel3.setBounds(580, 90, 190, 230);

        panel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        getContentPane().add(panel2);
        panel2.setBounds(0, 90, 90, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Version.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Version.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Version.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Version.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Version().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
